### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by dnKaratzas**

### CODE REVIEW

**Comment by sean7512** [comment]
Other than the merge conflict, is there anything holding this up? I'd love to get rid of cocoa pods in my projects. Thanks!

**Comment by crashoverride777** [comment]
Hey, thanks for your message and apologies for my lack of response previously.

So I totally understand the want to get rid of cocoa pods, I have done it myself recently in most of my projects after firebase added SwiftPackageManager support. All my open source libraries also have package manager support. This for me is not necessary the question of creating the package its mainly the way to handle the GoogleAdMobSDK dependency. 

1) How I can create  a SwiftPackage that requires the GoogleAdMobSDK which does not yet itself support SwiftPackageManager which means I cannot tell the package to use GoogleAdMob as a dependency.
2) How would you install GoogleAdMobSDK in your project without cocoa pods?.
3) I can only think of manually keeping the GoogleAdMobSDK framework folder in the package and manually manage it, which does not sound particularly great and I am not even sure that would work with swift package manager.

**Comment by sean7512** [comment]
Ahh, I didn't realize we were still waiting on Google, that is really annoying.

I think there would be 2 options...

1. Continue waiting on Google https://github.com/googleads/googleads-mobile-unity/issues/1125 (They claimed they were targeting August 2021 for SPM support, but nothing yet)
2. Use this library https://github.com/quanghits/GoogleMobileAds - the maintainer claims he updates it as the AdMobSDK is updated

I understand it is probably preferable to continue waiting on Google, as it really should be done *very* soon.

**Comment by kovelo** [comment]
@crashoverride777 Google has officially added SPM support for 9.3.0 https://github.com/googleads/swift-package-manager-google-mobile-ads

**Comment by crashoverride777** [comment]
Hey,

Thanks for that, that's some really nice news. Will open this issue again and get SPM ready by early may (currently on holiday)

**Comment by crashoverride777** [comment]
Hey,

I started integrating swift package manager. It went surprisingly well, the project is already building. Will aim to release this next week after some more testing. You fan follow the progress here https://github.com/crashoverride777/swifty-ads/tree/feature/swift-package-manager

**Comment by kovelo** [comment]
Wow that was fast and seemingly easy! Thanks for all of your hard work, incredibly appreciated

**Comment by crashoverride777** [comment]
Hey,

I have some good news :). I think the package manager migration was successful. I am currently overseas but will be back home on Monday, will try to release the update by Tuesday evening.
Screenshot 2022-04-30 at 13 54 54

**Pull request closed without merging**
